import { createClient } from "@/lib/supabase/server"
import { NextResponse } from "next/server"

interface RouteParams {
  params: Promise<{ entityId: string }>
}

export async function GET(_req: Request, { params }: RouteParams) {
  const { entityId } = await params
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { data, error } = await supabase
    .from("pt_invitations")
    .select("*")
    .eq("entity_id", entityId)
    .order("created_at", { ascending: false })

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ invitations: data })
}

export async function POST(request: Request, { params }: RouteParams) {
  const { entityId } = await params
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const body = await request.json()
  const { member_id: existingMemberId, display_name, email, role, skip_email } = body

  let member: { id: string; email?: string | null } | null = null

  // Path A: invite an existing member by their member_id (placeholder / invited)
  if (existingMemberId) {
    const { data: existing, error: fetchErr } = await supabase
      .from("pt_members")
      .select("id, email, display_name, status")
      .eq("id", existingMemberId)
      .eq("entity_id", entityId)
      .single()

    if (fetchErr || !existing) {
      return NextResponse.json({ error: "Member not found" }, { status: 404 })
    }
    if (existing.status === "removed") {
      return NextResponse.json({ error: "Cannot invite a removed member" }, { status: 409 })
    }

    // Bump status to "invited" only if still placeholder
    if (existing.status === "placeholder") {
      await supabase
        .from("pt_members")
        .update({ status: "invited", invited_by: user.id, updated_at: new Date().toISOString() })
        .eq("id", existingMemberId)
    }

    member = existing
  }

  // Path B: create a brand-new invitation (and member) from a name/email
  if (!member) {
    if (!display_name?.trim()) {
      return NextResponse.json({ error: "display_name is required" }, { status: 400 })
    }

    if (email) {
      const { data: byEmail } = await supabase
        .from("pt_members")
        .select("id")
        .eq("entity_id", entityId)
        .eq("email", email)
        .neq("status", "removed")
        .maybeSingle()
      if (byEmail) member = byEmail
    }

    if (!member) {
      const { data: newMember, error: memberError } = await supabase
        .from("pt_members")
        .insert({
          entity_id: entityId,
          display_name: display_name.trim(),
          email: email || null,
          role: role ?? "member",
          status: "invited",
          invited_by: user.id,
        })
        .select()
        .single()
      if (memberError) return NextResponse.json({ error: memberError.message }, { status: 500 })
      member = newMember
    }
  }

  if (!member) {
    return NextResponse.json({ error: "Could not resolve member" }, { status: 500 })
  }

  // Create the invitation record (token generated by DB default)
  const { data: invitation, error: invError } = await supabase
    .from("pt_invitations")
    .insert({
      entity_id: entityId,
      member_id: member.id,
      invited_by: user.id,
      invite_email: member.email ?? email ?? null,
    })
    .select()
    .single()

  if (invError) return NextResponse.json({ error: invError.message }, { status: 500 })

  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000"
  const joinLink = `${siteUrl}/partnerships/join?token=${invitation.invite_token}`

  // Send email if we have an address, a Resend key, and skip_email is not set
  const recipientEmail = member.email ?? (email as string | undefined) ?? null
  if (recipientEmail && process.env.RESEND_API_KEY && !skip_email) {
    try {
      const { data: entityRow } = await supabase
        .from("pt_entities")
        .select("name")
        .eq("id", entityId)
        .single()
      const entityName = entityRow?.name ?? "a partnership"

      // Fetch the member's display name (may have been updated above)
      const { data: memberRow } = await supabase
        .from("pt_members")
        .select("display_name")
        .eq("id", member.id)
        .single()
      const recipientName = memberRow?.display_name ?? "there"

      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          from: process.env.RESEND_FROM_EMAIL ?? "noreply@my-plan.app",
          to: recipientEmail,
          subject: `You're invited to join ${entityName} on My Plan`,
          html: `
            <p>Hi ${recipientName},</p>
            <p>You've been invited to join <strong>${entityName}</strong> on My Plan Partnerships.</p>
            <p>
              <a href="${joinLink}"
                 style="background:#2563eb;color:#fff;padding:10px 24px;border-radius:6px;text-decoration:none;display:inline-block;margin-top:8px;font-weight:600;">
                Accept Invitation
              </a>
            </p>
            <p style="color:#6b7280;font-size:13px;margin-top:16px;">
              Or copy this link into your browser:<br/>
              <span style="color:#374151;">${joinLink}</span>
            </p>
            <p style="color:#6b7280;font-size:12px;margin-top:16px;">
              This link expires in 7 days. If you did not expect this invitation, you can safely ignore this email.
            </p>
          `,
        }),
      })
    } catch {
      // Email failure is non-fatal — the invitation record and link are still returned
    }
  }

  return NextResponse.json({ invitation, member, joinLink }, { status: 201 })
}
